### ISSUE TITLE
Discord users can edit the time themselves if it is wrong without having to call for help

### ISSUE THREAD

**Issue by tama** [tama/pogo-discord-mod-bot#21]
As of now the only way to correct raid times is to call someone with "manage channel" permission to manually change the time.
The solution is to have some kind of command to manually correct the time of an existing raid channel (mod-bot acting as a proxy).

**Comment by tama** [comment]
Important : have the bot log its action once it has received and executed the command (either by posting a message or in a file)

**Comment by nicolasblaye** [comment]
changing starting time is without consequences, but what about changing end time? We should change the channel name then no?

**Comment by tama** [comment]
Yes, the channel name should change to according to the new computed end time.
Ideally, the message posted in the raid should also be edited, but it's still not the case with the `!pokemon` command so it's not a high priority "feature"
