### ISSUE TITLE
Revamp raid announcement format

### ISSUE THREAD

**Issue by nicolasblaye** [tama/pogo-discord-mod-bot#9]
The query should be easier to use, notably for phone user

We should: 

- clear double space by itself
- take care of the @ issue (sometimes, the auto-correct on the phone places a space after a @)
- fix formatting for hours (9h10 should work)

That's all I can think of for now, I am sure we could find other small issue that would greatly improve the announcement feature

**Comment by tama** [comment]
> take care of the @ issue (sometimes, the auto-correct on the phone places a space after a @)

Discord behavior, using '@' means the user wants to mention someone.
One solution would be to drop the @XX:XX format and use XX:XX as the starting time (the algorithm to compute the end time is already done) instead of the ending time as of now.
-> `!raid egg5 gym 8:15` for a raid starting at 8:15 instead of `!raid egg5 gym @8:15`

**Comment by nicolasblaye** [comment]
Also, do you think we should remove the `!` ? I think it is safe because the command is executed in a secure channel.
What bother me is that my phone always add a space after a `!`. Or we could recognize any command in `[!raid, ! raid, raid]` ?

**Comment by tama** [comment]
The "!" is a marker to indicate that the message being posted is a command to the bot, removing it is ok but I'd rather keep it, and/or use another more accessible marker.

**Comment by nicolasblaye** [comment]
Seen on the discord poll:
```
si c'est possible pour facilité la vie des lanceurs d'alerte, quand un raid est commencé et pour éviter de faire des calculs qui peuvent être faux, on ne peut pas avoir un code pour mettre le temps restant?
comme demandé par maitre @Vigevigе
```

Also, keep @

**Comment by tama** [comment]
PR merged, issue closed.
